//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuAsistencias.Models
{
    using System;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcuDBEntities : DbContext
    {
        public EcuDBEntities()
            : base("name=EcuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<PermisosSalida> PermisosSalida { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

    }
}
