//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuAsistencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosSalida
    {
        public int ID { get; set; }
        public int IDAsistencia { get; set; }
        public System.DateTime HoraPermiso { get; set; }
        public System.TimeSpan TiempoPermisoHoras { get; set; }
        public int IdMotivo { get; set; }
        public string MotivoOtros { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
        public virtual Motivo Motivo { get; set; }
    }
}
