//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuAsistencias.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }

        [Display(Name = "Cédula")]
        public string Identificacion { get; set; }
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Display(Name = "Apellido")]
        public string Apellido { get; set; }
        [Display(Name = "Fecha Nacimiento")]
        public System.DateTime FechaNacimiento { get; set; }
        [Display(Name = "Estado")]
        public bool Activo { get; set; }
        [Display(Name = "Contraseña")]
        public string Contrasenia { get; set; }
        [Display(Name = "Hora de entrada")]
        public System.DateTime HorarioInicio { get; set; }
        [Display(Name = "Hora de Salida")]
        public System.DateTime HorarioFin { get; set; }
        [Display(Name = "Ingresar Contraseña")]
        public bool CambioContrasenia { get; set; }

        [Display(Name = "Rol")]
        public int IDRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual Rol Rol { get; set; }


        [NotMapped]
        public string NombreCompleto
        {
            get
            {
                return Nombre + " " + Apellido;
            }
        }
    }
}
